version: '3'

networks:
    jsebastinet:
        driver: bridge

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        image: nginx

        ports:
            - "443:443"

        networks:
            - jsebastinet

        volumes:
            - wp_data:/var/www/html

        restart: always

    mariadb:
        container_name: mariadb
        build:
            context:
                ./requirements/mariadb

        image: mariadb

        volumes:
            - db_data:/var/lib/mysql

        restart: always

        networks:
            - jsebastinet

        env_file:
            .env

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        image: wordpress

        depends_on:
            - mariadb
        
        volumes:
            - wp_data:/var/www/html
        
        restart: always
        
        networks:
            - jsebastinet
        
        env_file:
            .env
    
volumes:
    db_data:
        driver: local
        driver_opts:
          type: none
          device: ${HOME}/data/mysql
          o: bind

    wp_data:
        driver: local
        driver_opts:
            type: none
            device: ${HOME}/data/wordpress
            o: bind
