version: '3'

networks:
    jsebastinet:
        driver: bridge

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        image: nginx

        ports:
            - "443:443"

        networks:
            - jsebastinet

        volumes:
            - wp_data:/var/www/html

        restart: always

    mariadb:
        container_name: mariadb
        build:
            context:
                ./requirements/mariadb

        image: mariadb

        volumes:
            - mariadb_data:/var/lib/mysql

        restart: always

        networks:
            - jsebastinet

        env_file:
            .env

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        image: wordpress

        depends_on:
            - mariadb
            - redis
        
        volumes:
            - wp_data:/var/www/html
        
        restart: always
        
        networks:
            - jsebastinet
        
        env_file:
            .env
    
    redis:
        container_name: redis
        build: ./requirements/bonus/redis
        image: redis

        volumes:
            - redis_data:/data

        ports:
            - "6379:6379"

        restart: always

        networks:
            - jsebastinet

        env_file:
            .env

    filezila:
        container_name: filezila
        build: ./requirements/bonus/filezila
        image: filezila

        ports:
            - "21:21"
            - "20:20"
            - "30000-30009:30000-30009"

        restart: always

        networks:
            - jsebastinet

        env_file:
            .env

volumes:
    mariadb_data:
        driver: local
        driver_opts:
          type: none
          device: ${HOME}/data/mysql
          o: bind

    wp_data:
        driver: local
        driver_opts:
            type: none
            device: ${HOME}/data/wordpress
            o: bind

    redis_data:
        driver: local
        driver_opts:
            type: none
            device: ${HOME}/data/redis
            o: bind