version: '3'

networks:
	jsebastinet:
		name: jsebastinet
		driver: bridge

services:
	nginx:
		container_name: nginx
		build: ./requirements/nginx
		image: nginx

		ports:
			- "433:433"

		networks:
			- jsebastinet

		volumes:
			- wordpress_data:/var/www/html

		restart: always

	mariadb:
		container_name: mariadb
		build:
			context:
				./requirements/mariadb

		image: mariadb

		volumes:
			- wordpress_data:/var/www/html

		restart: always

		networks:
			- jsebastinet

		env_file:
			.env

	wordpress:
		container_name: wordpress
		build: ./requirements/wordpress
		image: wordpress

		depends_on:
			- mariadb
		
		volumes:
			- wordpress_data:/var/www/html
		
		restart: always
		
		networks:
			- jsebastinet
		
		env_file:
			.env

volumes:
	mariadb_data:
	    driver: local
	    driver_opts:
	      type: none
	      device: /home/jsebasti/data/mysql
	      o: bind

	worpress_data:
		driver: local
		driver_opts:
			type: none
			device: /home/jsebasti/data/wordpress
			o: bind